using Godot;

namespace FTT.UI {

    /// <summary>
    /// Placeholder consumer for Chronal Rewind presentation events: cyan screen
    /// tint, scanline strips, and music ducking through the audio bus. Production
    /// post-processing replaces the visuals through this same event contract.
    /// </summary>
    public partial class RewindPresentationOverlay : CanvasLayer {
        /// <summary>Placeholder rewind cue assets (Package 8 B6, generated by
        /// <c>tools/generate_placeholder_audio.py</c>).</summary>
        public const string ReverseSweepPath = "res://audio/sfx/chronal/rewind_sweep.ogg";
        public const string ClockTickPath = "res://audio/sfx/chronal/clock_tick.ogg";

        private ColorRect _tint;
        private Control _scanlines;
        private bool _musicDucked;

        // Package 8 B6: the three payload fields that shipped with no consumer.
        private readonly RewindCueState _cues = new();
        private RewindGhostTrail _ghostTrail;
        private AudioStream _sweepStream;
        private AudioStream _tickStream;
        private bool _cueStreamsResolved;

        /// <summary>Cue/trail state, exposed for the presentation contract tests.</summary>
        public RewindCueState Cues => _cues;

        public override void _Ready() {
            Layer = 80;
            ProcessMode = ProcessModeEnum.Always;
            Visible = false;

            _tint = new ColorRect { Name = "Tint", Color = new Color(0f, 0.85f, 0.9f, 0.18f) };
            _tint.SetAnchorsPreset(Control.LayoutPreset.FullRect);
            _tint.MouseFilter = Control.MouseFilterEnum.Ignore;
            AddChild(_tint);

            _scanlines = new Control { Name = "Scanlines", MouseFilter = Control.MouseFilterEnum.Ignore };
            _scanlines.SetAnchorsPreset(Control.LayoutPreset.FullRect);
            AddChild(_scanlines);
            for (int index = 0; index < 27; index++) {
                var line = new ColorRect {
                    Color = new Color(0f, 0.9f, 0.95f, 0.08f),
                    Position = new Vector2(0, index * 40),
                    Size = new Vector2(1920, 3),
                    MouseFilter = Control.MouseFilterEnum.Ignore
                };
                _scanlines.AddChild(line);
            }

            BuildCollapseTreatment();

            if (FTT.Core.EventBus.Instance != null)
                FTT.Core.EventBus.Instance.OnRewindPresentation += OnRewindPresentation;
        }

        // === Timeline Collapse beat treatment (V7.3) ========================
        // The collapse phase reads differently from a rewind: the era
        // desaturates toward Archive monochrome behind chronal crack lines,
        // with the Sarah extraction line and — once the beat has been seen —
        // a press-to-skip prompt. Placeholder visuals on the same event
        // contract production post-processing will replace.

        private Control _collapseTreatment;
        private Label _collapseSkipPrompt;
        private Label _transmissionLine;

        /// <summary>
        /// The Sarah transmission over the collapse beat. Package 12 W1 (M17):
        /// hidden in Act III, which has no extraction. Test seam.
        /// </summary>
        public Label TransmissionLine => _transmissionLine;

        /// <summary>The fracture treatment root. Test seam.</summary>
        public Control CollapseTreatment => _collapseTreatment;

        /// <summary>The press-to-skip prompt. Test seam.</summary>
        public Label CollapseSkipPrompt => _collapseSkipPrompt;

        private void BuildCollapseTreatment() {
            _collapseTreatment = new Control {
                Name = "CollapseTreatment",
                MouseFilter = Control.MouseFilterEnum.Ignore,
                Visible = false
            };
            _collapseTreatment.SetAnchorsPreset(Control.LayoutPreset.FullRect);
            AddChild(_collapseTreatment);

            // Archive-monochrome desaturation wash.
            var wash = new ColorRect {
                Name = "MonochromeWash",
                Color = new Color(0.06f, 0.06f, 0.08f, 0.55f),
                MouseFilter = Control.MouseFilterEnum.Ignore
            };
            wash.SetAnchorsPreset(Control.LayoutPreset.FullRect);
            _collapseTreatment.AddChild(wash);

            // Chronal crack lines radiating from the death point (placeholder:
            // fixed diagonal shards).
            for (int index = 0; index < 6; index++) {
                var crack = new ColorRect {
                    Name = $"CrackLine{index}",
                    Color = new Color(0.95f, 0.45f, 0.25f, 0.5f),
                    Position = new Vector2(160 + index * 300, 0),
                    Size = new Vector2(4, 1080),
                    Rotation = (index % 2 == 0 ? 1 : -1) * (0.2f + index * 0.06f),
                    MouseFilter = Control.MouseFilterEnum.Ignore
                };
                _collapseTreatment.AddChild(crack);
            }

            _transmissionLine = new Label {
                Name = "TransmissionLine",
                Text = Tr("collapse_transmission_line"),
                HorizontalAlignment = HorizontalAlignment.Center,
                MouseFilter = Control.MouseFilterEnum.Ignore
            };
            _transmissionLine.SetAnchorsPreset(Control.LayoutPreset.CenterBottom);
            _transmissionLine.Position = new Vector2(-400, -180);
            _transmissionLine.CustomMinimumSize = new Vector2(800, 30);
            _collapseTreatment.AddChild(_transmissionLine);

            _collapseSkipPrompt = new Label {
                Name = "CollapseSkipPrompt",
                Text = Tr("collapse_skip_prompt"),
                HorizontalAlignment = HorizontalAlignment.Center,
                MouseFilter = Control.MouseFilterEnum.Ignore,
                Visible = false
            };
            _collapseSkipPrompt.SetAnchorsPreset(Control.LayoutPreset.CenterBottom);
            _collapseSkipPrompt.Position = new Vector2(-400, -130);
            _collapseSkipPrompt.CustomMinimumSize = new Vector2(800, 24);
            _collapseTreatment.AddChild(_collapseSkipPrompt);
        }

        public override void _ExitTree() {
            if (FTT.Core.EventBus.Instance != null)
                FTT.Core.EventBus.Instance.OnRewindPresentation -= OnRewindPresentation;
            if (_musicDucked) SetMusicDuck(0f);
            _cues.Reset();
            if (GodotObject.IsInstanceValid(_ghostTrail)) _ghostTrail.SetActive(false);
        }

        private void OnRewindPresentation(FTT.Core.RewindPresentationPayload payload) {
            bool active = payload.Phase == FTT.Core.RewindPresentationPhase.Started
                || payload.Phase == FTT.Core.RewindPresentationPhase.Playback
                || payload.Phase == FTT.Core.RewindPresentationPhase.TimelineCollapse;
            bool collapse = payload.Phase == FTT.Core.RewindPresentationPhase.TimelineCollapse;
            // C01a (Package 11 A8): the preset takes precedence over what the
            // authored payload asks for. High-frequency scanlines and decorative
            // ghost trails are suppressed outright; the flat screen tint stays,
            // because it is the stable cue identifying the time state and the
            // reduced treatment explicitly preserves that.
            bool scanlines = payload.ScanlinesEnabled && FTT.Core.ComfortSettings.DistortionAllowed;
            Visible = active && (payload.ScreenTintEnabled || scanlines);
            if (_tint != null) _tint.Visible = payload.ScreenTintEnabled && active;
            if (_scanlines != null) _scanlines.Visible = scanlines && active && !collapse;
            // V7.3 collapse beat: the fracture treatment replaces the rewind
            // scanline read; the skip prompt shows only once the beat has
            // been seen (the first viewing is unskippable).
            if (_collapseTreatment != null) _collapseTreatment.Visible = collapse;
            if (_collapseSkipPrompt != null) _collapseSkipPrompt.Visible = collapse && payload.CollapseSkipPromptEnabled;
            // Package 12 W1 (M17): the payload names the transmission — the
            // ordinary extraction line, the timer's era-lost variant, or none at
            // all in Act III, where no rift comes and nobody pulls the hero out.
            if (collapse && _transmissionLine != null) {
                string key = payload.TransmissionLineKey ?? "";
                _transmissionLine.Visible = key.Length > 0;
                if (key.Length > 0) _transmissionLine.Text = Tr(key);
            }
            // Package 12 W1 (R03): the recovery duck is held through the
            // Post-Landing Hold (a Landed payload carrying a duck) and released
            // at the thaw (the Thawed phase carries none).
            bool holdsDuck = active || payload.Phase == FTT.Core.RewindPresentationPhase.Landed;
            SetMusicDuck(holdsDuck ? payload.MusicDuckDecibels : 0f);

            bool playSweep = _cues.Apply(payload);
            // C01a: "Remove trailing copies of actors and props." The trail is
            // decorative after-imagery, not a readability cue, so it goes — and
            // passing false here also CLEARS copies already emitted, which is the
            // half the contract calls out about enabling the preset mid-effect.
            ApplyGhostTrail(_cues.GhostTrailActive && FTT.Core.ComfortSettings.GhostTrailsAllowed);
            if (playSweep) PlayCue(SweepStream());
        }

        /// <summary>
        /// Pumps the clock-tick cadence. Runs on <c>_Process</c> rather than
        /// <c>_PhysicsProcess</c> because it is presentation, and with
        /// <c>ProcessModeEnum.Always</c> because a rewind may pause the tree.
        /// </summary>
        private bool _appliedReducedEffects;

        public override void _Process(double delta) {
            // C01a applies live, including mid-rewind: enabling the preset must
            // clear already-emitted after-images and stop the suppressed overlay
            // now, not at the next event. Polled rather than event-subscribed
            // because a static event on a per-scene overlay is a leak waiting to
            // happen, and this node already runs every frame.
            if (_appliedReducedEffects != FTT.Core.ComfortSettings.ReducedTemporalEffects) {
                _appliedReducedEffects = FTT.Core.ComfortSettings.ReducedTemporalEffects;
                if (_appliedReducedEffects) {
                    ApplyGhostTrail(false);
                    if (_scanlines != null) _scanlines.Visible = false;
                }
            }
            int ticks = _cues.Advance((float)delta);
            if (ticks <= 0) return;
            // One cue per frame however far the clock slipped: a stall must not
            // dump a burst of ticks into the voice pool.
            PlayCue(TickStream());
        }

        private void ApplyGhostTrail(bool active) {
            if (active && !GodotObject.IsInstanceValid(_ghostTrail)) {
                _ghostTrail = RewindGhostTrail.EnsureInstalled(this);
            }
            if (GodotObject.IsInstanceValid(_ghostTrail)) _ghostTrail.SetActive(active);
        }

        private void PlayCue(AudioStream stream) {
            if (stream == null) return;
            FTT.Core.AudioManager.Instance?.PlayOneShot(
                stream, FTT.Core.AudioBuses.Environmental);
        }

        private AudioStream SweepStream() { ResolveCueStreams(); return _sweepStream; }

        private AudioStream TickStream() { ResolveCueStreams(); return _tickStream; }

        // Audio streams are streamed presentation, not authored tuning data, so they
        // load through ResourceLoader and deliberately not through AuthoredResources.
        private void ResolveCueStreams() {
            if (_cueStreamsResolved) return;
            _cueStreamsResolved = true;
            if (ResourceLoader.Exists(ReverseSweepPath)) {
                _sweepStream = ResourceLoader.Load<AudioStream>(ReverseSweepPath);
            }
            if (ResourceLoader.Exists(ClockTickPath)) {
                _tickStream = ResourceLoader.Load<AudioStream>(ClockTickPath);
            }
        }

        /// <summary>
        /// Ducks music for the rewind through the shared snapshot layer.
        ///
        /// <para>This used to snapshot the Music bus's absolute dB on entry and write
        /// it back on exit, which quietly reverted any volume change the player made
        /// mid-rewind and fought anything else that touched the bus. The snapshot
        /// mixer instead holds the duck as an <em>offset</em> over whatever base
        /// volume the settings own, and tweens it in and out.</para>
        ///
        /// <para>The authored depth still wins: <c>MusicDuckDecibels</c> from the
        /// rewind payload is passed through rather than using the snapshot's
        /// default.</para>
        /// </summary>
        private void SetMusicDuck(float decibels) {
            FTT.Core.AudioManager audio = FTT.Core.AudioManager.Instance;
            if (audio == null) return;
            if (decibels != 0f) {
                audio.ApplySnapshot(FTT.Core.AudioSnapshot.Rewind, decibels);
                _musicDucked = true;
            } else if (_musicDucked) {
                audio.ReleaseSnapshot(FTT.Core.AudioSnapshot.Rewind);
                _musicDucked = false;
            }
        }
    }
}
