using Godot;

namespace FTT.UI {

    /// <summary>
    /// Placeholder consumer for Chronal Rewind presentation events: cyan screen
    /// tint, scanline strips, and music ducking through the audio bus. Production
    /// post-processing replaces the visuals through this same event contract.
    /// </summary>
    public partial class RewindPresentationOverlay : CanvasLayer {
        /// <summary>Placeholder rewind cue assets (Package 8 B6, generated by
        /// <c>tools/generate_placeholder_audio.py</c>).</summary>
        public const string ReverseSweepPath = "res://audio/sfx/chronal/rewind_sweep.ogg";
        public const string ClockTickPath = "res://audio/sfx/chronal/clock_tick.ogg";

        private ColorRect _tint;
        private Control _scanlines;
        private bool _musicDucked;

        // Package 8 B6: the three payload fields that shipped with no consumer.
        private readonly RewindCueState _cues = new();
        private RewindGhostTrail _ghostTrail;
        private AudioStream _sweepStream;
        private AudioStream _tickStream;
        private bool _cueStreamsResolved;

        /// <summary>Cue/trail state, exposed for the presentation contract tests.</summary>
        public RewindCueState Cues => _cues;

        public override void _Ready() {
            Layer = 80;
            ProcessMode = ProcessModeEnum.Always;
            Visible = false;

            _tint = new ColorRect { Name = "Tint", Color = new Color(0f, 0.85f, 0.9f, 0.18f) };
            _tint.SetAnchorsPreset(Control.LayoutPreset.FullRect);
            _tint.MouseFilter = Control.MouseFilterEnum.Ignore;
            AddChild(_tint);

            _scanlines = new Control { Name = "Scanlines", MouseFilter = Control.MouseFilterEnum.Ignore };
            _scanlines.SetAnchorsPreset(Control.LayoutPreset.FullRect);
            AddChild(_scanlines);
            for (int index = 0; index < 27; index++) {
                var line = new ColorRect {
                    Color = new Color(0f, 0.9f, 0.95f, 0.08f),
                    Position = new Vector2(0, index * 40),
                    Size = new Vector2(1920, 3),
                    MouseFilter = Control.MouseFilterEnum.Ignore
                };
                _scanlines.AddChild(line);
            }

            if (FTT.Core.EventBus.Instance != null)
                FTT.Core.EventBus.Instance.OnRewindPresentation += OnRewindPresentation;
        }

        public override void _ExitTree() {
            if (FTT.Core.EventBus.Instance != null)
                FTT.Core.EventBus.Instance.OnRewindPresentation -= OnRewindPresentation;
            if (_musicDucked) SetMusicDuck(0f);
            _cues.Reset();
            if (GodotObject.IsInstanceValid(_ghostTrail)) _ghostTrail.SetActive(false);
        }

        private void OnRewindPresentation(FTT.Core.RewindPresentationPayload payload) {
            bool active = payload.Phase == FTT.Core.RewindPresentationPhase.Started
                || payload.Phase == FTT.Core.RewindPresentationPhase.Playback
                || payload.Phase == FTT.Core.RewindPresentationPhase.TimelineCollapse;
            Visible = active && (payload.ScreenTintEnabled || payload.ScanlinesEnabled);
            if (_tint != null) _tint.Visible = payload.ScreenTintEnabled && active;
            if (_scanlines != null) _scanlines.Visible = payload.ScanlinesEnabled && active;
            SetMusicDuck(active ? payload.MusicDuckDecibels : 0f);

            bool playSweep = _cues.Apply(payload);
            ApplyGhostTrail(_cues.GhostTrailActive);
            if (playSweep) PlayCue(SweepStream());
        }

        /// <summary>
        /// Pumps the clock-tick cadence. Runs on <c>_Process</c> rather than
        /// <c>_PhysicsProcess</c> because it is presentation, and with
        /// <c>ProcessModeEnum.Always</c> because a rewind may pause the tree.
        /// </summary>
        public override void _Process(double delta) {
            int ticks = _cues.Advance((float)delta);
            if (ticks <= 0) return;
            // One cue per frame however far the clock slipped: a stall must not
            // dump a burst of ticks into the voice pool.
            PlayCue(TickStream());
        }

        private void ApplyGhostTrail(bool active) {
            if (active && !GodotObject.IsInstanceValid(_ghostTrail)) {
                _ghostTrail = RewindGhostTrail.EnsureInstalled(this);
            }
            if (GodotObject.IsInstanceValid(_ghostTrail)) _ghostTrail.SetActive(active);
        }

        private void PlayCue(AudioStream stream) {
            if (stream == null) return;
            FTT.Core.AudioManager.Instance?.PlayOneShot(
                stream, FTT.Core.AudioBuses.Environmental);
        }

        private AudioStream SweepStream() { ResolveCueStreams(); return _sweepStream; }

        private AudioStream TickStream() { ResolveCueStreams(); return _tickStream; }

        // Audio streams are streamed presentation, not authored tuning data, so they
        // load through ResourceLoader and deliberately not through AuthoredResources.
        private void ResolveCueStreams() {
            if (_cueStreamsResolved) return;
            _cueStreamsResolved = true;
            if (ResourceLoader.Exists(ReverseSweepPath)) {
                _sweepStream = ResourceLoader.Load<AudioStream>(ReverseSweepPath);
            }
            if (ResourceLoader.Exists(ClockTickPath)) {
                _tickStream = ResourceLoader.Load<AudioStream>(ClockTickPath);
            }
        }

        /// <summary>
        /// Ducks music for the rewind through the shared snapshot layer.
        ///
        /// <para>This used to snapshot the Music bus's absolute dB on entry and write
        /// it back on exit, which quietly reverted any volume change the player made
        /// mid-rewind and fought anything else that touched the bus. The snapshot
        /// mixer instead holds the duck as an <em>offset</em> over whatever base
        /// volume the settings own, and tweens it in and out.</para>
        ///
        /// <para>The authored depth still wins: <c>MusicDuckDecibels</c> from the
        /// rewind payload is passed through rather than using the snapshot's
        /// default.</para>
        /// </summary>
        private void SetMusicDuck(float decibels) {
            FTT.Core.AudioManager audio = FTT.Core.AudioManager.Instance;
            if (audio == null) return;
            if (decibels != 0f) {
                audio.ApplySnapshot(FTT.Core.AudioSnapshot.Rewind, decibels);
                _musicDucked = true;
            } else if (_musicDucked) {
                audio.ReleaseSnapshot(FTT.Core.AudioSnapshot.Rewind);
                _musicDucked = false;
            }
        }
    }
}
